name: BUILD
#  branches:
#    - '!gh-pages'
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if dependencies are there
        run: |
          sudo apt update
          sudo apt-get install ruby-full build-essential zlib1g-dev
      - name: Pre setup gem locations
        run: sudo gem install jekyll bundler
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Get the actual dependencies
        run: sudo bundle install
      - name: Get the other branches
        run: |
          for version in $(cat versions.json | jq -r -c '.[]'); do
            git checkout -t ${version}
          done; git checkout gh-pages
      - name: Build the other branches
        run: ./update_docs.sh
      - name: Push the new changes
        run: |
          git config --global user.name 'BuildBot (GHA)'
          git config --global user.email 'clics@icpc.global'
          #git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          #git checkout "${GITHUB_REF:11}"
          git commit -am "Automated report"
          git push
      #- uses: actions/checkout@v3
      #  with:
      #    ref: gh-pages
      #    fetch-depth: 0
