name: CI

on:
  push:
    branches:
      - '!gh-pages'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the other branches
        run: ./update_docs.sh
