name: BUILD
#  branches:
#    - '!gh-pages'
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Build the other branches
        run: ./update_docs.sh
